services:
  api:
    image: catalog-api
    build: .
    environment:
      PORT: "8080"
      NODE_ENV: "production"
      GC_PROJECT_ID: "peaksellchromeextension"
      FIRESTORE_DATABASE: "nip-catalogs"
      CLIENT_ID: "${CLIENT_ID}"
      CLIENT_SECRET: "${CLIENT_SECRET}"
    ports:
      - "8080:8080"
